image: Visual Studio 2017

build_script:
  - nuget restore
  - msbuild /p:Configuration="Release"  /p:Targets="Build" /verbosity:quiet  /p:BuildInParallel=true /m

test:
  - nunit3-console MemoryGame_1B_Tests.dll --result=myresults.xml;format=AppVeyor